version: "3.9"
services:
  backend:
    image: backend:latest
    container_name: backend
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - local.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - local.env
    depends_on:
      backend:
        condition: service_healthy
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - local.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  redis:
    image: redis:7.2.1
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - local.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
